name: Android Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.2

      - name: Setup haxelib
        run: haxelib setup ~/haxelib

      - name: Install Android SDK + NDK
        uses: android-actions/setup-android@v3

      - name: Install SDK / NDK Components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-34"
          sdkmanager "build-tools;34.0.0"
          sdkmanager "ndk;21.4.7075529"

      - name: Set Android Environment Variables
        run: |
          echo "ANDROID_SDK=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/21.4.7075529" >> $GITHUB_ENV

      - name: Install Haxe Libraries
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hxcpp
          haxelib git flxanimate https://github.com/Dot-Stuff/flxanimate
          haxelib install haxeui-core
          haxelib install haxeui-flixel
          haxelib install hscript-iris
          haxelib install extension-androidtools
          haxelib run lime setup
          haxelib run lime setup android
          haxelib run lime rebuild hxcpp

      - name: Build APK
        run: haxelib run lime build android -release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HitSingleReal-Android
          path: export/android/bin/app/build/outputs/apk/release/*.apk